import { AppConfig } from './app-config.type';
import { AppleConfig } from '../auth-apple/config/apple-config.type';
import { AuthConfig } from '../auth/config/auth-config.type';
import { DatabaseConfig } from '../database/config/database-config.type';
import { FileConfig } from '../files/config/file-config.type';
import { GoogleConfig } from '../auth-google/config/google-config.type';
import { MailConfig } from '../mail/config/mail-config.type';
import { VeroConfig } from 'src/auth-vero/config/vero-config.type';
import { GorushConfig } from 'src/providers/gorush/config/gorush-config.type';
import { RabbitMQConfig } from 'src/communication/rabbitMQ/config/rabbitmq-config.type';
import { MinIOConfig } from '../providers/minio/config/minio-config.type';
import { SocketIOConfig } from '../communication/socketio/config/socketio-config.type';
import { CmcConfig } from '../providers/cmc/config/cmc-config.type';
import { BinanceConfig } from '../providers/binance/config/binance-config.type';
import { AwsSecretsManagerConfig } from './types/aws-secrets-manager-config.type';
import { FireblocksConfig } from '../providers/fireblocks/cw/config/fireblocks-config.type';
import { QueueDashConfig } from '../common/queuedash/config/queuedash-config.type';
import { InternalEventsConfig } from '../common/internal-events/config/internal-events-config.type';
import { CacheConfig } from '../common/cache/config/cache-config.type';

export type AllConfigType = {
  app: AppConfig;
  apple: AppleConfig;
  auth: AuthConfig;
  database: DatabaseConfig;
  file: FileConfig;
  google: GoogleConfig;
  mail: MailConfig;
  vero: VeroConfig;
  gorush: GorushConfig;
  rabbitMQ: RabbitMQConfig;
  minIO: MinIOConfig;
  socketIO: SocketIOConfig;
  cmc: CmcConfig;
  binance: BinanceConfig;
  awsSecretsManager: AwsSecretsManagerConfig;
  fireblocks: FireblocksConfig;
  queuedash: QueueDashConfig;
  internalEvents: InternalEventsConfig;
  cache: CacheConfig;
};
